### ISSUE TITLE
Can you support python3?

### ISSUE THREAD

**Issue by bywbilly** [btaba/yarlp#2]
Or just give some ideas how could I modify the code to support python3.

Thanks!

**Comment by bywbilly** [comment]
I figured it out by `pip3 install -e ./`.

**Comment by btaba** [comment]
hey thanks for checking out the package! I developed with python3 exclusively

**Comment by btaba** [comment]
If you have issues installing you can use the docker build or check out the travis yaml: https://github.com/btaba/yarlp/blob/master/.travis.yml#L9
